/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConfigItemTemplate: typeof import('./../src/components/templateRenderCompents/configItemTemplate.vue')['default']
    copy: typeof import('./../src/components/templateRenderCompents/mr_title copy.vue')['default']
    M_button: typeof import('./../src/components/templateRenderCompents/m_button.vue')['default']
    M_image: typeof import('./../src/components/templateRenderCompents/m_image.vue')['default']
    M_pUpload: typeof import('./../src/components/templateRenderCompents/m_pUpload.vue')['default']
    MaterialNodeTemplate: typeof import('./../src/components/templateRenderCompents/materialNodeTemplate.vue')['default']
    Mr_title: typeof import('./../src/components/templateRenderCompents/mr_title.vue')['default']
    PrewButton: typeof import('./../src/components/materialConfigCompent/PrewButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnoCSSIconButton: typeof import('./../src/components/Icon/UnoCSSIconButton.vue')['default']
  }
}
